DETAILED_ROUTE_STRATEGY_MISSING = "Missing routes only"
DETAILED_ROUTE_STRATEGY_RECENT = "Recent fetch only"
DEFAULT_DETAILED_ROUTE_STRATEGY = DETAILED_ROUTE_STRATEGY_MISSING


def detailed_route_strategy_labels():
    return [
        DETAILED_ROUTE_STRATEGY_MISSING,
        DETAILED_ROUTE_STRATEGY_RECENT,
    ]
