sonar.projectKey=ebelo_qfit
sonar.organization=ebelo
sonar.projectName=qfit

sonar.sources=.
sonar.tests=tests
sonar.exclusions=dist/**,.git/**,.github/**,__pycache__/**,*.pyc,tests/**
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
