sonar.projectKey=ebelo_qfit
sonar.organization=ebelo
sonar.projectName=qfit

sonar.sources=.
sonar.tests=tests
sonar.exclusions=dist/**,.git/**,.github/**,__pycache__/**,*.pyc,tests/**
sonar.test.inclusions=tests/**/*.py
sonar.coverage.exclusions=__init__.py,gpkg_writer.py,layer_manager.py,qfit_config_dialog.py,qfit_dockwidget.py,qfit_plugin.py,scripts/**/*.py
sonar.python.coverage.reportPaths=coverage.xml
