"""Compatibility re-exports for pre-#805 wizard composition imports.

The canonical shell composition implementation now lives in
``qfit.ui.dockwidget.workflow_composition``. Keep this module as a stable
wizard-named import path while the dock consolidation continues.
"""

from __future__ import annotations

from .workflow_composition import (
    AnalysisPageContent,
    AnalysisPageState,
    AtlasPageContent,
    AtlasPageState,
    ConnectionPageContent,
    ConnectionPageState,
    DockWizardPageSpec,
    DockWizardProgress,
    MapPageContent,
    MapPageState,
    SyncPageContent,
    SyncPageState,
    WizardActionCallbacks,
    WizardCompositionPage,
    WizardPage,
    WizardPageStateSnapshots,
    WizardProgressFacts,
    WizardSettingsSnapshot,
    WizardShell,
    WizardShellComposition,
    WizardShellPresenter,
    WorkflowProgressFacts,
    WorkflowStepPage,
    build_default_wizard_page_specs,
    build_placeholder_wizard_shell,
    build_wizard_page_states_from_facts,
    connect_wizard_action_callbacks,
    refresh_wizard_shell_composition,
)
from .workflow_composition import (
    DockWorkflowActionCallbacks,
    DockWorkflowPageSpec,
    DockWorkflowProgress,
    WorkflowCompositionPage,
    WorkflowPage,
    WorkflowPageStateSnapshots,
    WorkflowSettingsSnapshot,
    WorkflowShell,
    WorkflowShellComposition,
    WorkflowShellPresenter,
    build_default_workflow_page_specs,
    build_placeholder_workflow_shell,
    build_workflow_page_states_from_facts,
    connect_workflow_action_callbacks,
    refresh_workflow_shell_composition,
)

__all__ = [
    "AnalysisPageContent",
    "AnalysisPageState",
    "AtlasPageContent",
    "AtlasPageState",
    "ConnectionPageContent",
    "ConnectionPageState",
    "DockWorkflowActionCallbacks",
    "DockWorkflowPageSpec",
    "DockWorkflowProgress",
    "DockWizardPageSpec",
    "DockWizardProgress",
    "MapPageContent",
    "MapPageState",
    "SyncPageContent",
    "SyncPageState",
    "WizardActionCallbacks",
    "WizardCompositionPage",
    "WizardPage",
    "WizardPageStateSnapshots",
    "WizardProgressFacts",
    "WizardSettingsSnapshot",
    "WizardShell",
    "WizardShellComposition",
    "WizardShellPresenter",
    "WorkflowCompositionPage",
    "WorkflowPage",
    "WorkflowPageStateSnapshots",
    "WorkflowProgressFacts",
    "WorkflowSettingsSnapshot",
    "WorkflowShell",
    "WorkflowShellComposition",
    "WorkflowShellPresenter",
    "WorkflowStepPage",
    "build_default_workflow_page_specs",
    "build_default_wizard_page_specs",
    "build_placeholder_workflow_shell",
    "build_placeholder_wizard_shell",
    "build_workflow_page_states_from_facts",
    "build_wizard_page_states_from_facts",
    "connect_workflow_action_callbacks",
    "connect_wizard_action_callbacks",
    "refresh_workflow_shell_composition",
    "refresh_wizard_shell_composition",
]
